version: '3.8'

services:
  web:
    environment:
      - APACHE_RUN_USER=#1000
    build:
      context: ./docker/web
    ports:
      - 10001:80
    volumes:
      - ./src:/var/www/html
      - ./docker/web/default.conf:/etc/apache2/sites-enabled/000-default.conf